mysql:
  master:
    addr: localhost:3306
    user: root
    passwd: oliver
    dbname: hs
    pool: 500
    debug: true

redis:
  master:
    addr: 122.226.73.141:6379
    pool: 100

#log setup
log:
  #can set output to file, others will be outputed to std
  output: std
  name: log.txt
  #level can be: all, info, debug, warn, error, fatal
  level: all
